substituicoes_campeonatos = {
    'Brasileirão Betano': 'Brasileiro',
    'Copa Betano do Brasil': 'Copa do Brasil',
    'FIFA Club World Cup': 'Copa do Mundo de Clubes',
    'Brasileirão Série B': 'Brasileiro Série B',
    'CONMEBOL Libertadores': 'Libertadores',
    'CONMEBOL Sudamericana': 'Sul-Americana',
    'Mineiro Módulo I': 'Mineiro',
    'Paulista Série A1': 'Paulista',
    'Carioca Série A – Taça Guanabara': 'Carioca',
    'Gaúcho - Mata-mata': 'Gaúcho',
    'Baiano, Série A': 'Baiano',
    'Cearense, Série A': 'Cearense',
    'CONMEBOL Recopa': 'Recopa Sul-Americana',
    'Cearense, Série A': 'Cearense',
    'Mineiro Módulo I - Troféu Inconfidência': 'Mineiro - Troféu Inconfidência',
    'Goiano, 1ª Divisão': 'Goiano',
    'UEFA Europa League': 'Liga Europa',
    'UEFA Champions League': 'Liga dos Campeões',
    'UEFA Conference League': 'Conference League',
    'UEFA Europa Conference League': 'Conference League',
    'NM Cup': 'Copa da Noruega',
    'Primera A': 'Colombiano',
    'Svenska Cupen': 'Copa da Suécia',
    'Liga de Primera': 'Chileno',
    'Liga AUF Uruguaya': 'Uruguaio',
    'J1 League': 'Japonês',
    'Primera Division': 'Venezuelano',
    'Copa Venezuela': 'Copa da Venezuela',
    'División Profesional': 'Boliviano',
    'Copa Division Profesional': 'Copa da Bolívia',
    'Super Cup': 'Supercopa',
    'Copa Colombia': 'Copa da Colombia',
    'Liga 1': 'Peruano',
    'Premier Division': 'Irlandês',
    'LigaPro Serie A': 'Equatoriano',
    'Eliteserien': 'Norueguês',
    'Copa Argentina': 'Copa da Argentina',
    'Gaucho': 'Gaúcho',
    'Allsvenskan': 'Sueco',
    'Supercopa Internacional': 'Supercopa da Argentina',
    'Liga Profesional de Fútbol': 'Argentino',
    'Copa Chile': 'Copa do Chile',
    'Copa Ecuador': 'Copa do Equador',
    'Supercopa': 'Supercopa do Equador',
    'Leinster Senior Cup': 'Copa da Liga da Irlanda',
    'FAI Presidents Cup': 'Supercopa da Irlanda',
    'Emperor Cup': 'Copa do Imperador',
    'J. League Cup': 'Copa da Liga do Japão',
    'FAI Cup': 'Copa da Irlanda',
    'División de Honor': 'Paraguaio',
    'Svenska Cupen': 'Copa da Suécia',
    'Supercopa Uruguaya': 'Supercopa do Uruguai',
    'Supercopa Venezuela': 'Supercopa da Venezuela',
    'Community Shield': 'Supercopa da Inglaterra',
    'FA Cup': 'Copa da Inglaterra',
    'EFL Cup': 'Copa da Liga Inglesa',
    'LaLiga': 'La Liga',
    'Supercopa de España': 'Supercopa da Espanha',
    'Copa del Rey': 'Copa do Rei',
    'Coppa Italia': 'Copa da Itália',
    'Supercoppa Italiana': 'Supercopa da Itália',
    'DFL Supercup': 'Supercopa da Alemanha',
    'Supercup': 'Supercopa da Alemanha',
    'DFB Pokal': 'Copa da Alemanha',
    'Trophée des Champions': 'Supercopa da França',
    'Coupe de France': 'Copa da França',
    'Liga Portugal Betclic': 'Português',
    'Taça de Portugal': 'Copa de Portugal',
    'League Cup': 'Copa da Liga Portuguesa',
    'Johan Cruijff Schaal': 'Supercopa da Holanda',
    'KNVB beker': 'Copa da Holanda',
    'Ukraine Cup': 'Copa da Ucrânia',
    'Trendyol Süper Lig': 'Turco',
    'Super Kupa': 'Supercopa da Turquia',
    'Turkiye Kupasi': 'Copa da Turquia',
    'Stoiximan Super League': 'Grego',
    'Greek Football Cup': 'Copa da Grécia',
    'Saudi Pro League': 'Saudita',
    "King's Cup": 'Copa da Arábia',
    'UEFA Super Cup': 'Supercopa da Europa',
    'Liga dos Campeões da UEFA': 'Liga dos Campeões',
    'AFC Champions League Elite': 'Liga dos Campeões da Ásia',
    'CONCACAF Champions Cup': 'Copa dos Campeões da Concacaf',
    'Liga MX': 'Mexicano',
    'Supercopa Liga MX': 'Supercopa da Liga Mexicana',
    'Russian Cup': 'Copa da Rússia',
    'Danish Superliga': 'Dinamarquês',
    'Oddset Pokalen': 'Copa da Dinamarca',
    'Pro League': 'Belga',
    'Beker van Belgie': 'Copa da Bélgica',
    'Primera LPF': 'Argentino',
    'World Cup Qualificação': 'Eliminatórias',
    'Int. Friendly Games': 'Amistoso',
    'CONMEBOL Copa América': 'Copa América',
    'UEFA Nations League': 'Nations League',
    'Euro': 'Eurocopa',
    'World Cup Qual. UEFA L': 'Eliminatórias',
    'World Cup Qual. UEFA K': 'Eliminatórias',
    'World Cup Qual. UEFA J': 'Eliminatórias',
    'World Cup Qual. UEFA H': 'Eliminatórias',
    'World Cup Qual. UEFA A': 'Eliminatórias',
    'World Cup Qual. UEFA G': 'Eliminatórias',
    'World Cup Qual. UEFA E': 'Eliminatórias',
    'World Cup Qual. UEFA B': 'Eliminatórias',
    'World Cup Qual. UEFA C': 'Eliminatórias',
    'World Cup Qual. UEFA D': 'Eliminatórias',
    'World Cup Qual. UEFA F': 'Eliminatórias',
    'World Cup Qual. UEFA I': 'Eliminatórias',
    'FIFA World Cup': 'Copa do Mundo',
    'World Cup Qualification': 'Eliminatórias',
    'World Cup Qualificação': 'Eliminatórias',
    'CONCACAF Gold Cup': 'Copa Ouro',
    'FIFA Intercontinental Cup': 'Mundial de Clubes',
    'Primera División': 'Paraguaio',
    'Liga Profesional': 'Argentino',
    'Russian Cup Regions Path': 'Copa da Rússia',
}