'https://www.sofascore.com/pt/football/match/fc-chernihiv-sc-chaika/PerbsmlFc#id:12622328',
'https://www.sofascore.com/pt/football/match/ucsa-kyiv-real-pharma-odesa/RerbszxUd#id:12622339',
'https://www.sofascore.com/pt/football/match/kudrivka-irpin-dinaz-vyshhorod/WWncsfwBc#id:12637666',
'https://www.sofascore.com/pt/football/match/fsc-mariupol-hirnyk-sport-horishni-plavni/ACrspQBc#id:12622337',
'https://www.sofascore.com/pt/football/match/sc-vilkhivtsi-fc-metalist-kharkiv/oqbsVWxe#id:12622340',
'https://www.sofascore.com/pt/football/match/mfc-metalurh-zaporizhzhia-victoria-sumy/TxkcsLOoc#id:12622326',
'https://www.sofascore.com/pt/football/match/fc-kulykiv-bilka-nyva-vinnytsia/hlksObMd#id:12625591',
'https://www.sofascore.com/pt/football/match/metalist-1925-lokomotyv-kyiv/dFXbsOMgc#id:12622335',
'https://www.sofascore.com/pt/football/match/sc-poltava-fc-trostianets/GtpcsaMCc#id:12622333',
'https://www.sofascore.com/pt/football/match/revera-1908-ivano-frankivsk-podillia-khmelnytsky/CCrsRWxe#id:12622334',
'https://www.sofascore.com/pt/football/match/skala-1911-stryi-fc-epicentr-dunaivtsi/cwEcsRbMd#id:12622331',
'https://www.sofascore.com/pt/football/match/fc-uzhhorod-prykarpattia-ivano-frankivsk/HCosLWrc#id:12622330',
'https://www.sofascore.com/pt/football/match/ahrobiznes-volochysk-mfc-mykolaiv/fMosnlQb#id:12622336',
'https://www.sofascore.com/pt/football/match/bukovyna-chernivtsi-nyva-ternopil/pgosLqr#id:12622332',
'https://www.sofascore.com/pt/football/match/fc-olimpia-savyntsi-mfc-kremin-kremenchuk/GTrsQvkc#id:12622327',
'https://www.sofascore.com/pt/football/match/fc-khust-probiy-horodenka/okPcsNFKd#id:12622338',
# Rodada 2
'https://www.sofascore.com/pt/football/match/mfc-mykolaiv-fc-metalist-kharkiv/oqbsfMo#id:12649924',
'https://www.sofascore.com/pt/football/match/sc-poltava-metalist-1925/OMgcsaMCc#id:12649920',
'https://www.sofascore.com/pt/football/match/fc-kulykiv-bilka-probiy-horodenka/okPcsObMd#id:12649927',
'https://www.sofascore.com/pt/football/match/fc-chernihiv-victoria-sumy/TxkcsmlFc#id:12649922',
'https://www.sofascore.com/pt/football/match/bukovyna-chernivtsi-prykarpattia-ivano-frankivsk/HCosLqr#id:12649925',
'https://www.sofascore.com/pt/football/match/ucsa-kyiv-podillia-khmelnytsky/CCrszxUd#id:12649921',
'https://www.sofascore.com/pt/football/match/skala-1911-stryi-fc-minaj/tBqcsRbMd#id:12649923',
'https://www.sofascore.com/pt/football/match/fc-livyi-bereh-kyiv-kudrivka-irpin/fwBcsjofd#id:12649929',
'https://www.sofascore.com/pt/football/match/fc-olimpia-savyntsi-hirnyk-sport-horishni-plavni/ACrsQvkc#id:12649928',
# Rodada 3
'https://www.sofascore.com/pt/football/match/fc-olimpia-savyntsi-zorya-luhansk/MucsQvkc#id:12694171',
'https://www.sofascore.com/pt/football/match/probiy-horodenka-inhulets-petrove/ycFbsokPc#id:12694169',
'https://www.sofascore.com/pt/football/match/fc-minaj-victoria-sumy/TxkcstBqc#id:12694153',
'https://www.sofascore.com/pt/football/match/kolos-kovalivka-obolon-kyiv/owfbsBpFb#id:12694164',
'https://www.sofascore.com/pt/football/match/bukovyna-chernivtsi-mfc-mykolaiv/fMosLqr#id:12694158',
'https://www.sofascore.com/pt/football/match/karpaty-lviv-chornomorets-odesa/kqbsqqb#id:12694163',
'https://www.sofascore.com/pt/football/match/ucsa-kyiv-kudrivka-irpin/fwBcszxUd#id:12694168',
'https://www.sofascore.com/pt/football/match/metalist-1925-veres-rivne/ypFbsOMgc#id:12694166',
# Oitavos-de-Final
'https://www.sofascore.com/pt/football/match/rukh-lviv-karpaty-lviv/qqbsURQb#id:12767356',
'https://www.sofascore.com/pt/football/match/probiy-horodenka-bukovyna-chernivtsi/LqrsokPc#id:12767360',
'https://www.sofascore.com/pt/football/match/ucsa-kyiv-oleksandria/EjkszxUd#id:12767375',
'https://www.sofascore.com/pt/football/match/fc-kryvbas-kryvyi-rih-polissya-zhytomyr/LvdcsYFrc#id:12767362',
'https://www.sofascore.com/pt/football/match/vorskla-poltava-dynamo-kyiv/fqbsjqb#id:12767354',
'https://www.sofascore.com/pt/football/match/veres-rivne-obolon-kyiv/owfbsypFb#id:12767348',
'https://www.sofascore.com/pt/football/match/zorya-luhansk-shakhtar-donetsk/nqbsMuc#id:12767369',
'https://www.sofascore.com/pt/football/match/lnz-cherkasy-victoria-sumy/TxkcsCNnc#id:12767377',
# Quartas de final
'https://www.sofascore.com/pt/football/match/victoria-sumy-bukovyna-chernivtsi/LqrsTxkc#id:13107550',
'https://www.sofascore.com/pt/football/match/oleksandria-shakhtar-donetsk/nqbsEjk#id:13107549',
'https://www.sofascore.com/pt/football/match/polissya-zhytomyr-veres-rivne/ypFbsLvdc#id:13107555',
'https://www.sofascore.com/pt/football/match/rukh-lviv-dynamo-kyiv/fqbsURQb#id:13107548',
# Semifinais
'https://www.sofascore.com/pt/football/match/bukovyna-chernivtsi-dynamo-kyiv/fqbsLqr#id:13715019',
'https://www.sofascore.com/pt/football/match/polissya-zhytomyr-shakhtar-donetsk/nqbsLvdc#id:13715020',
# Final
'https://www.sofascore.com/pt/football/match/shakhtar-donetsk-dynamo-kyiv/fqbsnqb#id:13808883',